import React from "react";
// import { Route } from "react-router-dom";
import "./ShowBook.css";
// import FakeRatings from "./FakeRatings.js";
// import AmazonBuyButton from "./AmazonBuyButton.js";
import 'bulma/css/bulma.css';

//dummy import to get placeholder images
import placeholder_chart from '../images/placeholder_chart.png';

class ShowBook extends React.Component {
	constructor(props) {
		super(props);
		this.state = {
			authors: []
		};
	}

	async fetchBook() {
		console.log(
			"Going to fetch a book by its isbn10: " + this.props.match.params.id
		);

		// Getting the number of books and setting state to reflect that number
		fetch(`http://www.bookmatch.tk:3030/book?isbn10=${this.props.match.params.id}`)
			.then(response => response.json())
			.then(parsedJSON =>
				this.setState({
					title: parsedJSON.data[0].title,
					authors: parsedJSON.data[0].authors,
					ISBN10: parsedJSON.data[0].isbn10,
					ISBN13: parsedJSON.data[0].isbn13,
					summary: parsedJSON.data[0].summary,
					cover: parsedJSON.data[0].cover
				})
			);
	}

	componentDidMount(props) {
		console.log(this.props.location.state.existed);
		
		this.fetchBook();
	}

	render() {
		return (
		<div className="columns">	
			<div className="column is-3">
				<div>
					<figure className="image is-4x5 is-padded">
						<img src={this.state.cover} alt="Book Cover" />
					</figure>
				</div>
				<div />
				<div>
					<figure className="image is-1x1 is-padded">
						<img src={placeholder_chart} alt="Placeholder for chart generated by our ratings system" />
					</figure>
				</div>
			</div>
			<div className="column is-7">
				<div className="level">
					<div className="level-left">
						<div className="level-item is-size-4">
							{this.state.title}
						</div>
					</div>
				</div>
				<div className="level">
					<div className="level-left">
						<div className="level-item">
							<span>by </span>{this.state.authors.map((author, i) => <span key={i}> {author.name}  </span>)}
						</div>
					</div>
				</div>
				<div className="has-text-justified">
					{this.state.summary}
				</div>
			</div>
		</div>
		);
	}
}

export default ShowBook;
